/* Chapter from the book draft "My Body, My Habits" (full text, from sources/notion-my-body-my-habits.txt). One line per paragraph. */
window.POST = {
  "id": "ballet-2",
  "heading": "芭蕾（二）Ballet II: 我听见了，但我选择不听 / I Heard It, and I Looked Away",
  "note": "",
  "body": {
    "en": "I didn’t expect ballet to hurt.\nIt wasn’t immediate. At first it stayed quiet, like background noise. Then one day it wasn’t background anymore. The pain started gathering in my lower back, slowly, inside movements I didn’t fully understand.\nMy teacher speaks only German. Her instructions are fast and confident, and sometimes they pass through the room without landing in me. Sometimes I nod before I understand. Sometimes I move before I’m ready. And sometimes I realize too late that my body has been answering the wrong question.\nIt’s a strange kind of miscommunication, not exactly between two people, but between language and muscle, between what I mean and what I do. By the time I notice the mistake, it’s already stored somewhere in my body.\nAfter class, when it’s quiet again, I start to piece it together. A word I misheard. A direction I misunderstood. A movement that should have started somewhere else.\nThe strange part is that **my body knew before I did.** It was already giving me subtitles: tightness, heat, a dull ache in my lower back. I saw the subtitles, but I couldn’t read them yet.\nOr maybe I didn’t want to read them.\nAmbition has a way of making me selective. When I see classmates do something I can’t, I start pushing like it’s a moral duty. I turn it into a useless comparison, a useless race. And the one who gets damaged is always me.\nIt can feel like my brain is bullying my body: keep going, don’t be weak, don’t fall behind. My body answers in a language I’m supposed to understand, and I pretend I don’t.\nI do this outside the studio too. I ignore my own emotions the way I ignore early pain, assuming it will come over by itself, assuming time will clean it up. **But emotions are also signals.** They don’t disappear just because I refuse to translate them.\nRight now, my body understands faster than I do. I’m trying to respect the gap, and I’m trying to stop treating my own signals as interruptions.\nAffirmation: I listen when my body speaks, before ambition translates it into pressure.",
    "zh": "我没想到芭蕾会疼。\n它不是立刻就疼。起初它很安静，像背景噪音一样在那儿。后来有一天它突然不再是背景了。疼痛一点点聚到下背里，慢慢地，藏在那些我其实并没有完全弄懂的动作里。\n我的老师只讲德语。她的指令很快、很准、很笃定，但有时候它们只是穿过教室，并没有真的落到我身上。有时候我还没懂就先点头；有时候我还没准备好就先动；有时候我太晚才发现：我的身体一直在回答一个错误的问题。\n这是一种很奇怪的误会，不是纯粹发生在人与人之间，而是发生在语言和肌肉之间，发生在“我想做的”和“我实际做出来的”之间。等我意识到不对的时候，那个错误已经被身体存下来了，像存档一样，存在某个角落。\n下课以后，周围终于安静下来，我才开始一点点把它拼回去：一个词我听错了；一个方向我理解反了；一个动作本该从别的地方开始。\n奇怪的是，**身体比我更早知道。**它早就给我打了“字幕”：紧、热、下背那种钝钝的疼。我看见了字幕，却读不懂。\n又或者，我是不想读懂。\n野心会让我变得很“选择性失明”。尤其是当我看见同伴能做到、而我做不到的时候，我就会不自觉地加码：想追上，想证明，想不要落后。于是我把练习变成一种无用的比较，一种无用的竞赛。最后受损的，总是我自己。\n有时候那感觉很像：大脑在霸凌身体。它催着我：别停、别问、别示弱、别落后。身体用我本该听懂的语言回答我，而我假装听不见。\n这件事不只发生在教室里。我在生活里也常常这样忽略自己的感受：以为它们会“自己过去”，以为时间会把它们冲淡。**但情绪也是信号。**它们不会因为我不翻译，就自动消失。\n现在，是身体懂得比我快。我在练习尊重这段差距，也在练习别再把自己的信号当成打扰。\n收尾语：我会先听懂身体，再决定要不要用力。"
  }
};
