/* Chapter from the book draft "My Body, My Habits" (full text, from sources/notion-my-body-my-habits.txt). One line per paragraph. */
window.POST = {
  "id": "pole-2",
  "heading": "钢管舞（2）Pole Dance II: 它留给我的 / What It Gave Me",
  "note": "",
  "body": {
    "en": "What stayed with me from pole dance isn’t a skill.\nIt’s the way I started to see my own body.\nAt the beginning, it felt unfamiliar. Almost distant. I could look at it, but I didn’t really recognize it as something I belonged to. Every part felt separate, slightly disconnected, like I was learning it from the outside.\nThen came a phase of quiet dissatisfaction.\nI noticed things I didn’t like: the way certain movements looked, the way my body didn’t match what I thought it should be. It wasn’t dramatic. Just a subtle, constant sense that something was off.\nBut I kept showing up.\nAnd slowly, something shifted.\nI started paying attention differently. Not to fix, not to correct, but just to stay with the movement, to feel it from the inside. To notice how my body held me, how it adjusted, how it tried.\nOver time, that distance softened.\nI don’t think I suddenly started to find my body beautiful. It was something else.\nSomething closer, more forgiving.\nIf I had to describe it, I would call it a kind of indulgent affection. The kind where I stop demanding so much, and start allowing more. Where I can look at my body, all of it, and feel a quiet sense of closeness, even tenderness.\nAlmost like I’m a little biased toward it.\nI didn’t expect to feel that.\nAnd I know it didn’t come from getting better, or stronger, or meeting any standard.\nIt came from **staying with it long enough to stop treating it as a problem.**\nThat’s what I’m keeping.\nAffirmation: I’m so pretty every time I see the mirror.",
    "zh": "钢管舞留给我的，不是一项技能。\n而是我开始看见自己身体的方式。\n一开始，它很陌生，几乎有点遥远。\n我可以看见它，但我并不真正把它当作“我所属的东西”。\n身体的每一部分都像是分开的、轻微断裂的，好像我是在身体之外学习它。\n后来出现了一段安静的不满意。\n我注意到一些我不喜欢的地方：某些动作看起来的样子、我的身体和我以为“应该”有的样子不一致。\n它不戏剧化，只是一种很细、很持续的“哪里不对”。\n但我还是一次次出现。\n然后，慢慢地，有什么发生了变化。\n我开始以另一种方式注意：\n不是为了修正，不是为了纠错，而是为了留在动作里，从内部去感觉。\n去看我的身体如何托住我、如何调整、如何努力。\n时间久了，那种距离感变软了。\n我并不觉得自己突然就开始觉得身体“美”。\n更像是别的东西：\n更近一点，更宽容一点。\n如果一定要形容，我会说那是一种“偏爱”的温柔。\n一种我不再要求那么多、开始允许更多的温柔。\n一种我可以看着自己的身体，全部，感到一种安静的靠近，甚至带点怜爱。\n好像我开始有点偏向它。\n我没想到自己会有这种感觉。\n而且我知道，这不是来自我变强了、变厉害了、或达到了某个标准。\n它来自于：**我和身体待在一起足够久，久到我不再把它当作一个问题。**\n这就是我想保留的。\n收尾语：我每次照镜子都觉得自己好漂亮。"
  }
};
