/* Chapter from the book draft "My Body, My Habits" (full text, from sources/notion-my-body-my-habits.txt). One line per paragraph. */
window.POST = {
  "id": "pole-1",
  "heading": "钢管舞（1）Pole Dance I — 离开：对环境说“不” / Leaving: Saying No to the Frame",
  "note": "",
  "body": {
    "en": "I stopped going to pole dance classes.\nNot because I couldn’t do it. I had already learned everything required at Level 1.\nBut moving forward meant something else—an invert. Lifting my body upside down.可\nAnd I couldn’t do that yet.\nOn its own, that might have been fine. Strength takes time.\nWhat made it harder was everything around it.\nMy new teacher didn’t use music. The room became quieter, more technical, more distant.\nWhat remained felt like training for a requirement, not returning to myself.\nI started noticing how much the levels depended on specific skills.\nClear, effective, and also rigid.\nAs if my body could only be validated by moving through a predetermined checklist.\nI tried to work around it by joining mixed-level classes, where the atmosphere felt looser, more alive.\nBut there was only one class a week.\nSo I hesitated more and more before going.\nIt became something I had to convince myself to do.\nNot because I was curious, or excited, but because I felt like I should keep progressing.\nThe part I used to love—the rhythm, the flow, the feeling of moving with my body—slowly disappeared.\nLike I shouldn’t stop halfway.\nAt some point, I realized I was no longer enjoying it.\nIt felt like I was showing up for a system, not for myself.\nAt least, I had the courage to say no to that environment and leave.\nI still don’t know if this counts as giving up.\nListen honestly to your inner voice—even if it’s faint, listen closely.\nDon’t forget the original goal.\nWhen the goal is no longer there, feel into why, and then choose.\nBut I do know something changed—not just what I could do, but how I wanted to be there.\nAffirmation: Even if your inner voice is faint, choose for it.",
    "zh": "我停了钢管舞课。\n不是因为我做不到。Level 1 的要求，我其实已经学完了。\n但往前走意味着一个动作：倒挂（invert）。把自己整个人拎到空中，翻到上下颠倒。\n我还做不到。\n单看这一点，本来没什么——力量需要时间。\n难的是它周围的一切。\n新老师不上音乐。教室忽然安静下来，动作被拆得更细、更技术、更像在完成步骤。\n而我曾经最喜欢的部分——节奏、流动、和身体一起“跳”——慢慢消失了。\n剩下的更像是在训练一个门槛：为了达到要求而练，不是为了在身体里生活。\n我开始注意到“等级”是如何被某些固定技能绑住的。\n它很清晰，也很有效，却也很僵硬。\n我隐约不同意这种僵硬：好像身体只能沿着一条规定的路线被证明。\n我试着绕开它，去上混合水平的课。\n在那里，空气更松，人的动作也更像自己。\n但一周只有一节。\n于是我越来越犹豫。\n去上课变成一件需要说服自己的事。\n不是因为好奇，不是因为兴奋，而是因为一种“应该”：\n我不该停在这里。\n我不该半途而废。\n直到某一天，我发现我已经不再享受。\n我在为一个系统出席，而不是为自己。\n至少，我有勇气对那个环境说“不”，然后离开。\n我仍然不知道这算不算放弃。\n诚实地听从自己的内心声音，哪怕很弱，也要仔细听。\n不要忘了最初的目标。\n当目标不再时，感受一下原因，然后做出选择。\n但我知道，有什么东西变了——\n不只是我能不能倒挂，\n而是我想以怎样的方式在那根杆子旁边。\n收尾语：听见自己哪怕很弱的声音，也要为它做选择。"
  }
};
