/* Chapter from the book draft "My Body, My Habits" (full text, from sources/notion-my-body-my-habits.txt). One line per paragraph. */
window.POST = {
  "id": "taekwondo",
  "heading": "Taekwondo: Control Disguised as Discipline / 伪装成自律的控制",
  "note": "",
  "body": {
    "en": "I’m going to a taekwondo class today.\nI’ve been there before, just not recently. The last time was during graduate school. I biked 20 kilometers to get there, took the class, and went home exhausted. The next day, my knee was swollen. It didn’t hurt at all, which made it harder to understand. Later, I found out it was fluid from a meniscus issue. After that, I stopped exercising for two or three years.\nSo this time, I’m a little careful. Maybe a little afraid.\nI told myself I was preparing: looking up movements, reviewing terms. But that’s not the full story. The coach is someone I know. He knows me as someone athletic. I don’t want to show up as anything less.\nThis feeling isn’t new.\nDuring graduate school, I was at my most demanding with myself. I came from a small place and suddenly found myself in one of the top universities in China. I always felt like I wasn’t good enough. The people around me seemed to think so too: senior students, even professors. Someone once said it took me a whole year just to learn how to read papers properly.\nI carried that with me.\nI worked late, pushed hard, did everything I thought I was supposed to do. But it never felt like enough.\nI think that’s where this competitiveness comes from.\nIt’s a very specific kind. It only appears in front of people who already have an idea of me. Suddenly, I want to be better than I am.\nI’ve done this before. In school, I used to preview lessons, sometimes just ten minutes before class. It was enough. I could follow faster, answer quicker, seem ahead. That small head start always felt good.\nNow I’m doing the same thing again.\nEven with something like trampolining, I catch myself reading precautions, trying to understand everything before I even begin. **It looks like discipline, but it feels closer to control.**\nI think what I actually want from movement is not to win, or even to be good. I want to loosen this instinct, this need to get it right immediately, to prove something.\nBut I’m not trying to get rid of it.\nThis competitiveness, as strange as it is, has shaped me for a long time. It’s part of how I move through the world.\nI’m just learning how to move with it, instead of letting it lead.\nAffirmation: I can arrive as I am, and still be respected.",
    "zh": "我今天要去上跆拳道课。\n我以前去过，只是最近没有去。上一次还是读研的时候。我骑了二十公里自行车去道馆，上完课又骑回去，整个人累到散架。第二天我的膝盖肿了，但一点也不疼，这反而更让人难以理解。后来我才知道，那是半月板的问题导致的积液。之后我就几乎不运动了，两三年。\n所以这一次，我有点小心。也许还有点害怕。\n我告诉自己我是在“做准备”：查动作、背术语。但这不是全部的故事。教练是我认识的人。他认识的我，是“运动能力不错”的那种人。我不想让自己以一个更弱的样子出现。\n这种感觉其实并不新。\n读研的时候，我对自己最苛刻。我从一个很小的地方来到中国最好的大学之一，心里总觉得自己不够好。周围的人似乎也这样认为：师兄师姐，甚至一些老师。有人曾经说，我花了一整年才学会怎么正确读论文。\n这句话我一直带在身上。\n我熬夜、用力、把所有“应该做的”都做了，但还是总觉得不够。\n我想，我的竞争心大概就是从那里来的。\n它很具体：只会在那些“已经对我有印象”的人面前出现。那时我会突然想变得比现在更好，想立刻证明点什么。\n我以前就做过这样的事。上学时，我会提前预习，有时甚至只是上课前十分钟。那也足够让我跟得更快、回答更快、看起来更靠前。那一点点领先，总让我很舒服。\n现在我又在做同样的事。\n哪怕是蹦床这种运动，我也会忍不住先去读注意事项，想在开始之前先把一切弄懂。**它看起来像自律，但感觉更接近控制。**\n我觉得我真正想从运动里得到的，不是赢，甚至也不是“变得很厉害”。我想松动的是那个本能，那个一定要立刻做对、立刻证明自己的冲动。\n但我也不是想把它彻底消灭。\n这种竞争心，虽然奇怪，却很久以来塑造了我。它是我面对世界的一部分方式。\n我只是在学着：带着它一起动，而不是让它来带路。\n收尾语：我可以如实地抵达，也依然值得被尊重。"
  }
};
